api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: 1433
      transport: tcp
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: mssql-sa-password
        value: '{{ securedParameter "sql_password" }}'
  template:
    volumes:
      - name: sql-eshopapphostc8479139e4sqldata
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_SQL_VOLUME_ESHOPAPPHOSTC8479139E4SQLDATA_NAME }} 
    containers:
      - image: {{ .Image }}
        name: sql
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            secretRef: mssql-sa-password
        volumeMounts:
          - volumeName: sql-eshopapphostc8479139e4sqldata
            mountPath: /var/opt/mssql
    scale:
      minReplicas: 1
tags:
  azd-service-name: sql
  aspire-resource-name: sql
