// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Models;

#nullable disable

namespace Products.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DataEntities.Product", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasAnnotation("Relational:JsonPropertyName", "id");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasAnnotation("Relational:JsonPropertyName", "description");

                b.Property<string>("ImageUrl")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasAnnotation("Relational:JsonPropertyName", "imageUrl");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasAnnotation("Relational:JsonPropertyName", "name");

                b.Property<decimal>("Price")
                    .HasColumnType("TEXT")
                    .HasAnnotation("Relational:JsonPropertyName", "price");

                b.HasKey("Id");

                b.ToTable("Products");
            });
#pragma warning restore 612, 618
        }
    }
}
